### PR TITLE
Trying fix when pattern can be in between 2 READ_BUFFER_SIZE boundries

### PR DESCRIPTION
**Pull request by shadow2560**
I've done it as recommanded on Gbatemp but commented instructions are kept to show an other approach witch is more dynamic but need more INNER_HEAP_SIZE, I prefer you to give me your advice on this.

I've also renamed mov_cond3 to mov3_cond witch seems more logical to me to match the names used in the code.

### CODE REVIEW

**Comment by borntohonk** [comment]
as for heap sizes, errr, how much more does it need? due to memory footprints and whatnot keeping things within functional levels should be controlled

**Comment by shadow2560** [comment]
When set the overlap_size to 064f (line 413 and 414 in my PR) the INNER_HEAP_SIZE doesn't seems to be changed.

But in my PR if you commented the lines 413 and 414 and if you uncommented the lines from 453 to 461 and the line 473 the INNER_HEAP_SIZE must be ajusted but I don't realy know to what value, I've tried with 0x2000 and it worked but with 0x1000 this could freeze the console on the Nintendo Switch logo.

Personaly I prefer the second aproach even if it means to use twice the original INNER_HEAP_SIZE cause with this technic the size needed to fix the bug is automaticaly decided in function of the patch, with that we don't have to modify this anymore. I've chosen the first method on this PR because TotalJustice says that keeping the last 64 bytes should be enough and when I have tested it doesn't need to increase the INNER_HEAP_SIZE, like that nobody can tell me that Sys-patch will use too mutch memory. But I'm not an expert on all these subjects so I prefer to propose the two choices and let people that are more experienced than me to discus about them.

**Comment by borntohonk** [comment]
> When set the overlap_size to 064f (line 413 and 414 in my PR) the INNER_HEAP_SIZE doesn't seems to be changed.
> 
> But in my PR if you commented the lines 413 and 414 and if you uncommented the lines from 453 to 461 and the line 473 the INNER_HEAP_SIZE must be ajusted but I don't realy know to what value, I've tried with 0x2000 and it worked but with 0x1000 this could freeze the console on the Nintendo Switch logo.
> 
> Personaly I prefer the second aproach even if it means to use twice the original INNER_HEAP_SIZE cause with this technic the size needed to fix the bug is automaticaly decided in function of the patch, with that we don't have to modify this anymore. I've chosen the first method on this PR because TotalJustice says that keeping the last 64 bytes should be enough and when I have tested it doesn't need to increase the INNER_HEAP_SIZE, like that nobody can tell me that Sys-patch will use too mutch memory. But I'm not an expert on all these subjects so I prefer to propose the two choices and let people that are more experienced than me to discus about them.

If only thinking about sys-patch, of course we can be greedy and use much more memory, but reality unfortunately is that a lot of people boot with too many custom sysmodules which also expend memory, so keeping memory footprint low is done out of consideration as to not cause issues booting for the people who insist to "collect and use them all at the same time".

**Comment by shadow2560** [comment]
That's also why I've chosen the first aproach but in the other hand  it's only 4096 bytes more in memory, I don't know how mutch memory all the sysmodules can use at the same time on the Switch but even if we need to use 0x3000 instead of 0x1000 it's not realy so big. But for now we don't need to use the second aproach, after all if it works like that why not...

**Comment by borntohonk** [comment]
if syspatch frees up all the memory it's using after patching, it would be a non-issue

**Comment by shadow2560** [comment]
Yes, in all the functions that I'm working on I free the memory as soon as possible but during all the module execution I think the heap_size is reserved but Sys-patch just need one or two seconds max to do it job when console boot, that's why I think it can use a little more memory (it's not a reason to not maximize the optimization when we can). And when writing this message I'm remembered that we have the "main_thread_priority" property in the "sys-patch.json" file, we may use it to execute the module prior to others, I will read more on the json properties because I've never realy tried to understand them (it's my first module developement on the Switch, I need to learn).

**Pull request merged**
